---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
driver:
  name: podman
platforms:
  - name: centos7-dockerfile
    image: centos7-dockerfile:latest
    command: null
    pre_build_image: true
  - name: centos8-dockerfile
    image: centos8-dockerfile:latest
    command: null
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence: 
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
role_name_check: 1
